import type { SiteContent } from './types';

export const en = {
  meta: {
    title: 'Yulia Brynskikh — SMM Specialist · Marketing with an MBA base',
    description:
      'Yulia Brynskikh — SMM specialist based in Tashkent. Positioning, tone of voice, profile packaging, content systems and the audience path to action. Experience, the UNNI case, contacts.',
  },
  ui: {
    skipToContent: 'Skip to main content',
    brandLine: 'YULIA BRYNSKIKH · SMM SPECIALIST',
    brandAria: 'Yulia Brynskikh. Back to top',
    menu: 'Menu',
    close: 'Close',
    mainNavAria: 'Main navigation',
    mobileNavAria: 'Mobile navigation',
    telegramAria: 'Message Yulia on Telegram, opens in a new tab',
    emailAria: 'Email Yulia',
    cvLabel: 'CV (PDF)',
    cvAria: 'Open the CV as a PDF, opens in a new tab',
    headerCta: 'Say hello',
    languageAria: 'Site language',
    chapter: 'Chapter',
    mobileBarCta: 'Message on Telegram',
    footerRole: 'SMM / MARKETING',
    footerCity: 'Tashkent',
  },
  intro: {
    portfolio: 'PORTFOLIO / 00',
    cityYear: 'TASHKENT / 2026',
    noise: [
      '#reels',
      'STORIES',
      '♡ 1,284',
      'DIRECT',
      '24H',
      'SALE −30%',
      'NEW POST',
      '#trend',
      'REPOST',
      'HIGHLIGHTS',
      '▶ 12K',
      'LIKE',
      'COMMENT',
      '#kbeauty',
      'CTA',
      'REACH',
      'ER 4.2%',
      'SWIPE UP',
      'FOLLOW',
      'PROMO',
      '#sale',
      'LIVE',
      'ENGAGEMENT',
      'CAROUSEL',
      'UGC',
      'TREND',
      'HASHTAG',
      'REELS',
      'SAVES',
      '#new',
      'REVIEW',
      'BRIEF',
      'TOV',
      'FEED',
    ],
    keepers: ['VOICE', 'SYSTEM', 'ACTION'],
    nameFirst: 'Yulia',
    nameSecond: 'Brynskikh.',
    role: 'SMM SPECIALIST · MARKETING WITH AN MBA BASE',
    skipHint: 'Click to skip',
    signalLabel: 'NOISE → MEANING',
  },
  navigation: [
    { label: 'Approach', section: 'approach' },
    { label: 'Project', section: 'case' },
    { label: 'Experience', section: 'experience' },
    { label: 'Services', section: 'services' },
    { label: 'Process', section: 'process' },
    { label: 'About', section: 'about' },
    { label: 'Education', section: 'education' },
    { label: 'Contact', section: 'contact' },
  ],
  hero: {
    eyebrow: 'SMM SPECIALIST · MARKETING WITH AN MBA BASE',
    titleFirst: 'Yulia',
    titleSecond: 'Brynskikh.',
    description:
      'I help brands find their voice and turn audience attention into action: positioning, tone of voice, a content system and a clear path to the next step.',
    location: 'Tashkent · open to projects and roles',
    primaryCta: 'Message on Telegram',
    secondaryCta: 'See the UNNI project',
    facts: [
      { value: '2+', label: 'years in client service' },
      { value: 'Sab Lab', label: 'SMM manager · now' },
    ],
    strip: ['BRAND', 'AUDIENCE', 'CONTENT', 'ACTION'],
    portraitAlt: 'Yulia Brynskikh, SMM specialist',
  },
  method: {
    eyebrow: 'Approach',
    title: 'Content starts not with a format, but with a reason to stop scrolling.',
    description:
      'So I begin with the brand’s character and the task, then build the system — and only then choose formats.',
    items: [
      {
        id: 'voice',
        title: 'Voice',
        description: 'Positioning, tone of voice and the language the brand uses with people.',
        note: 'Not “like everyone else” — recognisable and right for a specific audience.',
        visual: {
          index: 'VOICE / 01',
          lines: ['Warm.', 'Clear.', 'To the point.'],
          note: 'You can hear the character before you remember the name.',
        },
      },
      {
        id: 'system',
        title: 'System',
        description: 'Profile packaging, content pillars, Stories, Reels and the logic of the content plan.',
        note: 'Every format gets a role of its own instead of existing for the sake of posting.',
        visual: {
          index: 'SYSTEM / 02',
          lines: ['REELS', 'STORIES', 'PROFILE', 'HIGHLIGHTS', 'PLAN', 'TOV'],
          note: 'Different formats. One logic.',
        },
      },
      {
        id: 'action',
        title: 'Action',
        description: 'The path from the first touch to the profile, Highlights, Direct and the order.',
        note: 'Content becomes part of the user’s route, not a standalone picture.',
        visual: {
          index: 'ACTION / 03',
          lines: ['CONTENT', 'PROFILE', 'DIRECT', 'ACTION'],
          note: 'Each step hints at the next one.',
        },
      },
    ],
  },
  caseStudy: {
    eyebrow: 'Project',
    title: 'UNNI — from brand character to the logic of communication.',
    summary:
      'A hands-on K-beauty project within an MBA programme: I brought positioning, visual packaging, a content system, the path to an order and a strategic base together into one solution.',
    disclaimer: 'Practical project · no invented commercial metrics',
    mediaProject: 'UNNI / SELECTED PROJECT',
    mediaSignature: 'Y.B. / 2026',
    steps: [
      {
        id: 'packaging',
        title: 'Account packaging',
        text: 'Built a single visual direction for the feed, designed the profile and planned Highlights so the catalogue, reviews, prices and delivery are found without extra taps.',
        label: 'PROFILE / HIGHLIGHTS / VISUAL',
      },
      {
        id: 'voice',
        title: 'Tone of voice',
        text: 'Defined the “caring older sister” persona: warm, clear, no jargon — with local context and skincare questions in mind.',
        label: 'POSITIONING / LANGUAGE / TRUST',
      },
      {
        id: 'funnel',
        title: 'Content and user path',
        text: 'Mapped the Stories and Reels logic: a useful video earns attention, the profile reveals the brand, Highlights answer questions and Direct becomes the natural step to an order.',
        label: 'REELS\u00A0→ PROFILE\u00A0→ HIGHLIGHTS\u00A0→ DIRECT',
      },
      {
        id: 'creators',
        title: 'Creator partnerships',
        text: 'Selected local K-beauty creators, checked their audiences for fake followers and wrote briefs for integrations that bring in the right subscribers.',
        label: 'FIT / AUDIENCE / BRIEF',
      },
      {
        id: 'strategy',
        title: 'Marketing base',
        text: 'Ran a SWOT/TOWS analysis, worked through pricing strategies (4P), shaped the USP and segmented the audience with local context in mind — so communication rests on the business, not only on visuals.',
        label: 'SWOT / TOWS / 4P / USP',
      },
    ],
  },
  experience: {
    eyebrow: 'Experience',
    title: 'Two years in client service — then the move into marketing.',
    description:
      'First — talking to customers face to face: service, objections, live feedback. Now — content, analytics and positioning. It is one path, not two separate ones.',
    totalValue: '2+',
    totalLabel: 'years in client service and communication',
    currentTag: 'Now',
    beforeMarketing: 'Before marketing',
    beforeMarketingNote: 'The roles where I learned to hear the customer.',
    caseLink: 'See the case',
    items: [
      {
        id: 'sablab',
        track: 'marketing',
        company: 'Sab Lab',
        role: 'SMM manager',
        period: 'August 2026 — present',
        location: 'Tashkent',
        current: true,
        summary:
          'Running and growing the company’s social media: from filming at events to analytics and content decisions.',
        highlights: [
          'Fast-turnaround event content and posts on the approved content plan',
          'Copy for posts, stories and publications; briefing and managing the design team',
          'Reach, engagement and pillar analytics; monitoring trends and competitors',
        ],
      },
      {
        id: 'unni',
        track: 'marketing',
        company: 'UNNI',
        role: 'SMM manager · MBA project',
        period: 'February — June 2026',
        location: 'Tashkent',
        summary:
          'Built the social media of a K-beauty online store from scratch — from positioning to a clear path to an order.',
        highlights: [
          'Positioning, tone of voice and profile packaging',
          'Content system and user path: Reels\u00A0→ profile\u00A0→ Highlights\u00A0→ Direct',
          'Creator selection and integration briefs; SWOT/TOWS, 4P and the USP behind the decisions',
        ],
        linkToCase: true,
      },
      {
        id: 'korean-time',
        track: 'people',
        company: 'Korean Time',
        role: 'Client relations manager',
        period: 'June — July 2026',
        summary:
          'Supported students and parents at a language centre: feedback, objection handling and choosing the right study format.',
        highlights: [],
      },
      {
        id: 'fidelity',
        track: 'people',
        company: 'Fidelity Investment',
        role: 'Office manager',
        period: 'December 2025 — June 2026',
        summary:
          'Kept the office of an IT integrator running: received and routed enquiries, prepared events and meetings.',
        highlights: [],
      },
      {
        id: 'willpower',
        track: 'people',
        company: 'WillPower fitness',
        role: 'Senior administrator',
        period: 'May 2024 — October 2025',
        summary:
          'Handled the client flow of a fitness club: consultations, conflict situations, cash desk, reporting and staff coordination.',
        highlights: [],
        result: 'Customer satisfaction doubled according to reviews; recognised by management for client focus.',
      },
    ],
  },
  services: {
    eyebrow: 'Services',
    title: 'What I can build into a clear system.',
    description:
      'Not a one-size-fits-all package, but specific tasks that add up to consistent brand communication.',
    items: [
      {
        title: 'Positioning and tone of voice',
        description: 'Brand character, key messages and the rules of talking to the audience.',
      },
      {
        title: 'Audience and competitor analysis',
        description: 'Segments, needs, the context of choice and real points of difference.',
      },
      {
        title: 'Profile packaging',
        description: 'Bio, navigation, Highlights and the visual direction of the account.',
      },
      {
        title: 'Content system',
        description: 'Pillars, content plan, Stories, Reels — and analytics of what actually works.',
      },
      {
        title: 'User path',
        description: 'The link between content, profile, Highlights and the next action.',
      },
      {
        title: 'Creator integrations',
        description: 'Initial creator selection, audience-fit assessment and brief preparation.',
      },
    ],
    footnoteLabel: 'Not a package for the sake of a package.',
    footnote: 'The scope is defined by the task, the product and where the brand is right now.',
  },
  process: {
    eyebrow: 'Process',
    title: 'From “what should we post?” to a working logic.',
    description: 'The process adapts to the task, but the sequence stays: understand, define, build, verify.',
    items: [
      { title: 'Discovery', description: 'We break down the product, task, audience, current point and constraints.' },
      { title: 'Research', description: 'I look at competitors, the customer path, current content and growth points.' },
      { title: 'Direction', description: 'We lock positioning, tone of voice, pillars and the visual logic.' },
      { title: 'Build', description: 'I assemble packaging, the content plan and materials into one system.' },
      { title: 'Adjust', description: 'We watch the audience’s reaction and refine the solution based on facts.' },
    ],
  },
  about: {
    eyebrow: 'About',
    title: 'Marketing with the customer in mind.',
    quote: 'Beautiful content can stop the eye. Clear content also explains why to go further.',
    paragraphs: [
      'I came to marketing through working with people: two years of consulting, feedback, objections and customer service. So I start not with a trend but with a question — what matters to the person and what stops them from taking the next step.',
      'I look at a project not as a content maker but as a strategist: I understand funnels, business processes and product goals. The base — an SMM specialist course and Mini MBA programmes.',
      'I pick up new tools quickly, am not afraid of unconventional tasks and take responsibility for the result.',
    ],
    facts: ['Tashkent', 'Strategy · content · analytics', 'SMM + MBA base', 'Open to projects and roles'],
  },
  education: {
    eyebrow: 'Education',
    title: 'Still building the marketing base — from SMM to management.',
    items: [
      {
        year: '2025',
        title: 'SMM Specialist course',
        provider: 'Tehnikum',
        kind: 'Diploma',
        description: 'Social media promotion, content planning, target audience and competitor analysis.',
      },
      {
        year: '2026',
        title: 'International Mini MBA programme',
        provider: 'Skillbox · Lerna · UBRAINS',
        kind: 'Certificate',
        description: 'A practical programme in management and business tools.',
      },
      {
        year: '2026',
        title: 'Professional Mini MBA programme',
        provider: 'Westminster International University in Tashkent',
        kind: 'Certificate',
        description: 'Management and strategy foundations.',
      },
      {
        year: '2026',
        title: 'MBA: Leadership and Strategic Management',
        provider: 'Skillbox',
        kind: 'Professional development',
        description: 'Approaches to leadership, management and decision-making.',
      },
    ],
  },
  contact: {
    eyebrow: 'Contact',
    title: 'Have a task or a role in mind? Let’s start with a conversation.',
    description:
      'Come with a ready brief, a job description or simply describe what is not working right now. We will figure out which next step is actually needed.',
    telegramLabel: 'Message on Telegram',
    emailLabel: 'Send an email',
    note: 'Telegram is the fastest way',
    indexCaption: "LET'S TALK",
  },
  contacts: {
    telegram: 'https://t.me/yulleishn',
    telegramHandle: '@yulleishn',
    email: 'theyullek4@mail.ru',
    instagram: null,
    cv: './downloads/yulia-brynskikh-cv.pdf',
  },
} as const satisfies SiteContent;
